### ISSUE TITLE
Request: a BBSteno layout

### ISSUE THREAD

**Issue by mhoye** [jthlim/javelin-steno#15]
The MechWild BBSteno layouts have an extra column of keys on the leftmost end. I'd like to add support for this layout to Javelin - ideally, have it appear in the layout pulldown, but I'm not sure where to start.

I can see you're not accepting contributions until you sort the CLA question. 

https://mechwild.com/product/bb-steno/

**Comment by jthlim** [comment]
For non-mainstream boards, I recommend you follow the guidance here on building a custom Javelin firmware: https://github.com/jthlim/javelin-steno-rp2040/issues/4

The firmware source has been made open so that anyone can support their own boards, but the overall project is not aiming to have every keyboard supported automatically

**Comment by mhoye** [comment]
Will do, thank you.
